## Title Here
An short introduction about PyTorch and about the chosen functions.

*   transpose(input, dim0, dim1)
*   permute(*dims)
*   poisson(input *, generator=None)
*   mul(input, other, *, out=None)
*   inverse(input, *, out=None)

Before we begin, let's install and import PyTorch

In [2]:
# Import torch and other required modules
import torch

## Function 1 - transpose(input, dim0, dim1)
Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

The resulting out tensor shares it’s underlying storage with the input tensor, so changing the content of one would change the content of the other.

### Parameter


*  input (Tensor) – the input tensor.

*  dim0 (int) – the first dimension to be transposed

*  dim1 (int) – the second dimension to be transposed





In [26]:
x = torch.rand(2,3)
x

tensor([[0.9953, 0.5487, 0.3824],
        [0.4103, 0.1943, 0.2185]])

In [27]:
x.transpose(0, 1)

tensor([[0.9953, 0.4103],
        [0.5487, 0.1943],
        [0.3824, 0.2185]])

Returns a tensor that is a transposed version of input. The dim0 and dim1 of x are swapped after we use this function.

In [12]:
y = torch.rand(2,3,4)
y

tensor([[[0.8931, 0.4512, 0.1932, 0.2029],
         [0.5693, 0.4101, 0.2117, 0.8268],
         [0.3268, 0.7633, 0.9164, 0.2549]],

        [[0.2594, 0.1393, 0.7299, 0.2018],
         [0.7563, 0.0903, 0.6125, 0.2235],
         [0.6437, 0.4035, 0.9248, 0.9582]]])

In [17]:
y.transpose(1, 0, 2)

TypeError: ignored

transpose() received an invalid combination of arguments 

Since transpose() function can only tanspose the dimension of 2-d array, we should use permute() function if our array dimenison is greater than 2.

## Function 2 - permute(*dims)

Returns a view of the original tensor with its dimensions permuted.

### Parameters

   
*dims (int...) – The desired ordering of dimensions

In [35]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [36]:
x.permute(2, 0, 1).size()

torch.Size([5, 2, 3])

In [37]:
x.permute(1, 0, 2).size()

torch.Size([3, 2, 5])

The difference between transpose and permute are two:


1.   We can use permute() to transpose the dimension for array which has more than two dimension.
2.   Unlike the parameter dim0 and dim1 in trnaspose(), the parameter in permute() will specify the dimension of array to be transposed.



In [38]:
x.permute(1, 0).size()

RuntimeError: ignored

Since the numbers of parameter will specify the dimension to be transposed, we need to list all desired ordering of dimensions.

Compared with transpose(), permute() offer a more flexible and powerful way to deal with dimension of array. However, when the dimension of the array is smaller than 2, we can us transpose() since it is more faster and easier to use.

## Function 3 - poisson(input *, generator=None)

Returns a tensor of the same size as input with each element sampled from a Poisson distribution with rate parameter given by the corresponding element in input

### Parameter
*  input (Tensor) – the input tensor containing the rates of the Poisson distribution

Keyword Arguments
*  generator (torch.Generator, optional) – a pseudorandom number generator for sampling

In [43]:
rates = torch.rand(4, 4) * 7  
rates

tensor([[1.3937, 5.1908, 5.4934, 6.7403],
        [3.8535, 3.1459, 3.7027, 0.8682],
        [5.3008, 2.1007, 0.7004, 0.0508],
        [4.2095, 1.2734, 5.8632, 3.3235]])

rate parameter between 0 and 7

In [44]:
torch.poisson(rates)

tensor([[4., 5., 4., 7.],
        [2., 3., 2., 1.],
        [1., 0., 0., 0.],
        [8., 0., 7., 3.]])

In [45]:
rates = torch.rand(4, 4) * 7  
torch.poisson(rates, generator=True)

TypeError: ignored

The default of parameter generator is false. We shoulde pass type of torch.Generator argument to the possion() function.

In [50]:
g_cpu = torch.Generator()
torch.poisson(rates, g_cpu)

tensor([[ 0., 10.,  0.,  4.],
        [ 0.,  0.,  0.,  4.],
        [ 1.,  3.,  7.,  2.],
        [ 2.,  2.,  8.,  0.]])

We can use Poisson distribution for modeling the times of event occurs in an unit time.

e.g. the interval of time that how many customer arrive to the system.

## Function 4 - mul(input, other, *, out=None)

Multiplies each element of the input input with the scalar other and returns a new resulting tensor.

In [5]:
a = torch.randn(3)
a

tensor([-1.0583, -1.9421,  2.1392])

In [4]:
torch.mul(a, 100)

tensor([-36.2101,  -7.3372, 102.0033])

Each element of the tensor input is multiplied by the corresponding element of the Tensor other. The resulting tensor is returned.

The shapes of input and other must be broadcastable.


Two tensors are “broadcastable” if the following rules hold:

*  Each tensor has at least one dimension.
*  When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.






In [7]:
a = torch.randn(4, 1)
print(a)
b = torch.randn(1, 4)
print(b)

tensor([[ 0.2842],
        [ 1.3236],
        [-1.7131],
        [ 0.2324]])
tensor([[-0.9203,  2.5977, -0.6928,  0.3643]])


In [8]:
torch.mul(a, b)

tensor([[-0.2615,  0.7382, -0.1969,  0.1035],
        [-1.2181,  3.4382, -0.9170,  0.4822],
        [ 1.5766, -4.4501,  1.1869, -0.6241],
        [-0.2139,  0.6036, -0.1610,  0.0847]])

In [11]:
c = torch.randn(2, 5)
c

tensor([[ 0.1515, -0.5707, -0.4039,  1.1750, -0.5356],
        [ 0.3113,  1.3546,  0.1664,  2.6099,  0.8421]])

In [12]:
torch.mul(a, c)

RuntimeError: ignored

The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0

Since this multiplication doesn't follow the rule of broadcasting, we can't use mul() to tensor a and c.

## Function 5 - inverse(input, *, out=None) 

Takes the inverse of the square matrix input. input can be batches of 2D square tensors, in which case this function would return a tensor composed of individual inverses.

In [27]:
x = torch.rand(4, 4)
x

tensor([[0.6608, 0.0792, 0.1032, 0.1746],
        [0.1351, 0.4932, 0.2039, 0.4134],
        [0.6811, 0.2472, 0.0158, 0.9620],
        [0.4757, 0.0524, 0.9137, 0.4896]])

In [28]:
y = torch.inverse(x)
y

tensor([[ 1.8436, -0.1944, -0.1687, -0.1620],
        [ 0.8494,  2.3920, -0.8692, -0.6146],
        [-0.1939,  0.2216, -0.6083,  1.0774],
        [-1.5204, -0.4808,  1.3923,  0.2549]])

In [29]:
z = torch.mm(x, y)
z

tensor([[ 1.0000e+00,  0.0000e+00, -7.4506e-08, -1.4435e-08],
        [-1.4901e-08,  1.0000e+00,  5.9605e-08,  2.9802e-08],
        [ 1.1921e-07, -7.4506e-08,  1.0000e+00, -1.4901e-08],
        [ 0.0000e+00, -2.2352e-08,  0.0000e+00,  1.0000e+00]])

The reason that except diagonal, other elements in array are not all zero is because the  small error in computer numericial system. 

In [30]:
x = torch.arange(9).reshape(3,3)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [31]:
torch.inverse(x)

RuntimeError: ignored

The computation of inverse matrix fails if the matrix is ​​singular. We can add (-1) * row1 and 2 * row2 to the row3.

This function is useful when we are dealing with linear algebra problems.

## Conclusion

In this notebook, we have discussed pytorch operation about transpose tensor, some statistic and linear algebra question.

## Reference Links

* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* https://towardsdatascience.com/5-statistical-functions-in-pytorch-2d75e3dcc1fd
